version: "3"

dotenv: [".env", "{{.ENV}}/.env.", "{{.HOME}}/.env"]

env:
  PYTHONPATH: "{{.ROOT_DIR}}/src"

tasks:
  preanalysis:
    cmds:
      - python src/preanalysis/analyse_five_minutes.py

  export:
    cmds:
      - python src/preanalysis/export_to_csv.py

  aggregate:
    cmds:
      - python src/preanalysis/aggregate_bars.py

  generate-images:
    cmds:
      - python src/preanalysis/clustering/generate_images.py

  cluster-images:
    cmds:
      - python src/preanalysis/clustering/cluster_images.py

  classify:
    cmds:
      - python src/preanalysis/clustering/classify.py
